# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 循环任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/zsh35/jd_scripts.git ~/jd_scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/jd_scripts
          git checkout my3
          npm install
      - name: '运行 【东东农场】'
        run: |
          cd ~/jd_scripts
          node jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【东东萌宠】'
        run: |
          cd ~/jd_scripts
          node jd_pet.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【口袋书店】'
        run: |
          cd ~/jd_scripts
          node jd_bookshop.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【京喜农场】'
        run: |
          cd ~/jd_scripts
          node jd_jxnc.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【宠汪汪积分兑换奖品】'
        run: |
          cd ~/jd_scripts
          node jd_joy_reward.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【宠汪汪偷好友积分与狗】'
        run: |
          cd ~/jd_scripts
          node jd_joy_steal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【点点券】'
        run: |
          cd ~/jd_scripts
          node jd_necklace.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【京东直播18豆】'
        run: |
          cd ~/jd_scripts
          node jd_live.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【京东天天加速】'
        run: |
          cd ~/jd_scripts
          node jd_speed.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【天天提鹅】'
        run: |
          cd ~/jd_scripts
          node jd_daily_egg.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
          
      - name: '运行 【金融养猪】'
        run: |
          cd ~/jd_scripts
          node jd_pigPet.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }} 

      - name: '运行 【东东超市】'
        run: |
          cd ~/jd_scripts
          node jd_superMarket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}

      - name: '运行 【京东家庭号】'
        run: |
          cd ~/jd_scripts
          node jd_family.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
